name: trecs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install project
        run: uv sync --all-groups
      - name: Lint the code
        run: uv run black --check .
      - name: Run type checks
        run: uv run pyright
      - name: Run the tests
        run: uv run pytest -v tests
